services:
    fenrizbes_publications.admin.publication:
        class: Fenrizbes\PublicationsBundle\Admin\PublicationAdmin
        arguments:
            - ~
            - Fenrizbes\PublicationsBundle\Model\Publication
            - SonataAdminBundle:CRUD
        calls:
            - [ setTranslationDomain, [ FenrizbesPublicationsBundle ] ]
            - [ setDateTimeFormat,    [ %fp.datetime_format% ] ]
            - [ setContentEditor,     [ %fp.sonata_admin.content_editor% ] ]
        tags:
            -
                name:              sonata.admin
                manager_type:      propel
                group:             %fp.sonata_admin.group_label%
                label:             fp.label.admin.publications
                show_in_dashboard: false

    fenrizbes_publications.admin.publication_type:
        class: Fenrizbes\PublicationsBundle\Admin\PublicationTypeAdmin
        arguments:
            - ~
            - Fenrizbes\PublicationsBundle\Model\PublicationType
            - SonataAdminBundle:CRUD
        calls:
            - [ setTranslationDomain, [ FenrizbesPublicationsBundle ] ]
        tags:
            -
                name:         sonata.admin
                manager_type: propel
                group:        %fp.sonata_admin.group_label%
                label:        fp.label.admin.publication_types
